@startuml
class Course {
    + CourseId : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Exams : Exam[0..m] <<get>> <<set>>
    + Topics : Topic[0..m] <<get>> <<set>>
    + <<override>> ToString() : string
}

Course --> Exam
Course --> Topic
@enduml
