@startuml
class Course {
    + CourseId : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + <<override>> ToString() : string
}
class "List`1"<T> {
}
Course --> "Exams<Exam>" "List`1"
Course --> "Topics<Topic>" "List`1"
@enduml
