@startuml
class Department {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Manager : Instructor <<get>> <<set>>
    + <<override>> ToString() : string
}
Department --> Instructor
@enduml
