@startuml
class Exam {
    + Id : int <<get>> <<set>>
    + CourseId : int <<get>> <<set>>
    + Questions : Question [1..m] <<get>> <<set>>
    + <<override>> ToString() : string
}

Exam --> Question
@enduml
