@startuml
class Instructor {
    + Courses : Course[0..m] <<get>> <<set>>
    + Department : Department <<get>> <<set>>
    + GenerateExam(courseId:int) : void
    + AssignExam(examId:int) : void
    + <<override>> ToString() : string
}

Person <|-- Instructor
Instructor --> Course
Instructor --> Department
@enduml
