@startuml
class Student {
    + Phone : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + Department : Department <<get>> <<set>>
    + Courses : Courses[1..m] <<get>> <<set>>
    + Exams : Exams[0..m] <<get>> <<set>>
    + TakeExam(id:int) : int
    + GetGrades() : List<Tuple<string, double>>
    + GetGrade(id:int) : Tuple<string, double>
    + <<override>> ToString() : string
}

Person <|-- Student
Student --> Department
Student --> Course
Student --> StudentExam
@enduml
