@startuml
!include .\\Examination System UML\Admin.puml
!include .\\Examination System UML\Course.puml
!include .\\Examination System UML\Department.puml
!include .\\Examination System UML\Exam.puml
!include .\\Examination System UML\Instructor.puml
!include .\\Examination System UML\Person.puml
!include .\\Examination System UML\Question.puml
!include .\\Examination System UML\Student.puml
!include .\\Examination System UML\StudentExam.puml
!include .\\Examination System UML\Topic.puml
@enduml
